/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as ApiConversaProvaRouteImport } from './routes/api/conversa-prova'
import { Route as AppUsuariosRouteImport } from './routes/_app.usuarios'
import { Route as AppRankingRouteImport } from './routes/_app.ranking'
import { Route as AppLeadsDiaRouteImport } from './routes/_app.leads-dia'
import { Route as AppIndicacoesRouteImport } from './routes/_app.indicacoes'
import { Route as AppFechamentoSemanalRouteImport } from './routes/_app.fechamento-semanal'
import { Route as AppFechamentoRouteImport } from './routes/_app.fechamento'
import { Route as AppComissionamentoRouteImport } from './routes/_app.comissionamento'
import { Route as AppCoachRouteImport } from './routes/_app.coach'
import { Route as AppCampanhaRouteImport } from './routes/_app.campanha'
import { Route as AppAgenteIaRouteImport } from './routes/_app.agente-ia'
import { Route as AppAgenteRouteImport } from './routes/_app.agente'
import { Route as AppArenaIndexRouteImport } from './routes/_app.arena.index'
import { Route as ApiPublicHotmartRawRouteImport } from './routes/api/public/hotmart-raw'
import { Route as ApiPublicHotmartProbeRouteImport } from './routes/api/public/hotmart-probe'
import { Route as ApiPublicHotmartDebugRouteImport } from './routes/api/public/hotmart-debug'
import { Route as ApiPublicBackfillV3RouteImport } from './routes/api/public/backfill-v3'
import { Route as ApiPublicBackfillContactTagsRouteImport } from './routes/api/public/backfill-contact-tags'
import { Route as ApiPublicBackfillAiExactRouteImport } from './routes/api/public/backfill-ai-exact'
import { Route as ApiHotmartWebhookRouteImport } from './routes/api/hotmart/webhook'
import { Route as ApiClintWebhookRouteImport } from './routes/api/clint/webhook'
import { Route as AppCoachIdRouteImport } from './routes/_app.coach.$id'
import { Route as ApiPublicSyncTriggerRouteImport } from './routes/api/public/sync.trigger'
import { Route as ApiPublicSyncHotmartRouteImport } from './routes/api/public/sync.hotmart'
import { Route as ApiPublicSyncContactTagsRouteImport } from './routes/api/public/sync.contact-tags'
import { Route as ApiPublicSyncCoachV3RouteImport } from './routes/api/public/sync.coach-v3'
import { Route as ApiPublicSyncCoachAutoRouteImport } from './routes/api/public/sync.coach-auto'
import { Route as ApiPublicSyncCcpbxRouteImport } from './routes/api/public/sync.ccpbx'
import { Route as ApiPublicAuditManualSalesRouteImport } from './routes/api/public/audit/manual-sales'
import { Route as ApiPublicAgendaBookRouteImport } from './routes/api/public/agenda.book'
import { Route as ApiPublicAgendaAvailabilityRouteImport } from './routes/api/public/agenda.availability'
import { Route as ApiPublicAdminManualSaleRouteImport } from './routes/api/public/admin.manual-sale'
import { Route as AppArenaSimIdRouteImport } from './routes/_app.arena.sim.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const ApiConversaProvaRoute = ApiConversaProvaRouteImport.update({
  id: '/api/conversa-prova',
  path: '/api/conversa-prova',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsuariosRoute = AppUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AppRoute,
} as any)
const AppRankingRoute = AppRankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => AppRoute,
} as any)
const AppLeadsDiaRoute = AppLeadsDiaRouteImport.update({
  id: '/leads-dia',
  path: '/leads-dia',
  getParentRoute: () => AppRoute,
} as any)
const AppIndicacoesRoute = AppIndicacoesRouteImport.update({
  id: '/indicacoes',
  path: '/indicacoes',
  getParentRoute: () => AppRoute,
} as any)
const AppFechamentoSemanalRoute = AppFechamentoSemanalRouteImport.update({
  id: '/fechamento-semanal',
  path: '/fechamento-semanal',
  getParentRoute: () => AppRoute,
} as any)
const AppFechamentoRoute = AppFechamentoRouteImport.update({
  id: '/fechamento',
  path: '/fechamento',
  getParentRoute: () => AppRoute,
} as any)
const AppComissionamentoRoute = AppComissionamentoRouteImport.update({
  id: '/comissionamento',
  path: '/comissionamento',
  getParentRoute: () => AppRoute,
} as any)
const AppCoachRoute = AppCoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => AppRoute,
} as any)
const AppCampanhaRoute = AppCampanhaRouteImport.update({
  id: '/campanha',
  path: '/campanha',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteIaRoute = AppAgenteIaRouteImport.update({
  id: '/agente-ia',
  path: '/agente-ia',
  getParentRoute: () => AppRoute,
} as any)
const AppAgenteRoute = AppAgenteRouteImport.update({
  id: '/agente',
  path: '/agente',
  getParentRoute: () => AppRoute,
} as any)
const AppArenaIndexRoute = AppArenaIndexRouteImport.update({
  id: '/arena/',
  path: '/arena/',
  getParentRoute: () => AppRoute,
} as any)
const ApiPublicHotmartRawRoute = ApiPublicHotmartRawRouteImport.update({
  id: '/api/public/hotmart-raw',
  path: '/api/public/hotmart-raw',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotmartProbeRoute = ApiPublicHotmartProbeRouteImport.update({
  id: '/api/public/hotmart-probe',
  path: '/api/public/hotmart-probe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHotmartDebugRoute = ApiPublicHotmartDebugRouteImport.update({
  id: '/api/public/hotmart-debug',
  path: '/api/public/hotmart-debug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackfillV3Route = ApiPublicBackfillV3RouteImport.update({
  id: '/api/public/backfill-v3',
  path: '/api/public/backfill-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicBackfillContactTagsRoute =
  ApiPublicBackfillContactTagsRouteImport.update({
    id: '/api/public/backfill-contact-tags',
    path: '/api/public/backfill-contact-tags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicBackfillAiExactRoute =
  ApiPublicBackfillAiExactRouteImport.update({
    id: '/api/public/backfill-ai-exact',
    path: '/api/public/backfill-ai-exact',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiHotmartWebhookRoute = ApiHotmartWebhookRouteImport.update({
  id: '/api/hotmart/webhook',
  path: '/api/hotmart/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiClintWebhookRoute = ApiClintWebhookRouteImport.update({
  id: '/api/clint/webhook',
  path: '/api/clint/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCoachIdRoute = AppCoachIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AppCoachRoute,
} as any)
const ApiPublicSyncTriggerRoute = ApiPublicSyncTriggerRouteImport.update({
  id: '/api/public/sync/trigger',
  path: '/api/public/sync/trigger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncHotmartRoute = ApiPublicSyncHotmartRouteImport.update({
  id: '/api/public/sync/hotmart',
  path: '/api/public/sync/hotmart',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncContactTagsRoute =
  ApiPublicSyncContactTagsRouteImport.update({
    id: '/api/public/sync/contact-tags',
    path: '/api/public/sync/contact-tags',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSyncCoachV3Route = ApiPublicSyncCoachV3RouteImport.update({
  id: '/api/public/sync/coach-v3',
  path: '/api/public/sync/coach-v3',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCoachAutoRoute = ApiPublicSyncCoachAutoRouteImport.update({
  id: '/api/public/sync/coach-auto',
  path: '/api/public/sync/coach-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSyncCcpbxRoute = ApiPublicSyncCcpbxRouteImport.update({
  id: '/api/public/sync/ccpbx',
  path: '/api/public/sync/ccpbx',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAuditManualSalesRoute =
  ApiPublicAuditManualSalesRouteImport.update({
    id: '/api/public/audit/manual-sales',
    path: '/api/public/audit/manual-sales',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAgendaBookRoute = ApiPublicAgendaBookRouteImport.update({
  id: '/api/public/agenda/book',
  path: '/api/public/agenda/book',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAgendaAvailabilityRoute =
  ApiPublicAgendaAvailabilityRouteImport.update({
    id: '/api/public/agenda/availability',
    path: '/api/public/agenda/availability',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicAdminManualSaleRoute =
  ApiPublicAdminManualSaleRouteImport.update({
    id: '/api/public/admin/manual-sale',
    path: '/api/public/admin/manual-sale',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppArenaSimIdRoute = AppArenaSimIdRouteImport.update({
  id: '/arena/sim/$id',
  path: '/arena/sim/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/auth': typeof AuthRouteWithChildren
  '/agente': typeof AppAgenteRoute
  '/agente-ia': typeof AppAgenteIaRoute
  '/campanha': typeof AppCampanhaRoute
  '/coach': typeof AppCoachRouteWithChildren
  '/comissionamento': typeof AppComissionamentoRoute
  '/fechamento': typeof AppFechamentoRoute
  '/fechamento-semanal': typeof AppFechamentoSemanalRoute
  '/indicacoes': typeof AppIndicacoesRoute
  '/leads-dia': typeof AppLeadsDiaRoute
  '/ranking': typeof AppRankingRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/conversa-prova': typeof ApiConversaProvaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/coach/$id': typeof AppCoachIdRoute
  '/api/clint/webhook': typeof ApiClintWebhookRoute
  '/api/hotmart/webhook': typeof ApiHotmartWebhookRoute
  '/api/public/backfill-ai-exact': typeof ApiPublicBackfillAiExactRoute
  '/api/public/backfill-contact-tags': typeof ApiPublicBackfillContactTagsRoute
  '/api/public/backfill-v3': typeof ApiPublicBackfillV3Route
  '/api/public/hotmart-debug': typeof ApiPublicHotmartDebugRoute
  '/api/public/hotmart-probe': typeof ApiPublicHotmartProbeRoute
  '/api/public/hotmart-raw': typeof ApiPublicHotmartRawRoute
  '/arena/': typeof AppArenaIndexRoute
  '/arena/sim/$id': typeof AppArenaSimIdRoute
  '/api/public/admin/manual-sale': typeof ApiPublicAdminManualSaleRoute
  '/api/public/agenda/availability': typeof ApiPublicAgendaAvailabilityRoute
  '/api/public/agenda/book': typeof ApiPublicAgendaBookRoute
  '/api/public/audit/manual-sales': typeof ApiPublicAuditManualSalesRoute
  '/api/public/sync/ccpbx': typeof ApiPublicSyncCcpbxRoute
  '/api/public/sync/coach-auto': typeof ApiPublicSyncCoachAutoRoute
  '/api/public/sync/coach-v3': typeof ApiPublicSyncCoachV3Route
  '/api/public/sync/contact-tags': typeof ApiPublicSyncContactTagsRoute
  '/api/public/sync/hotmart': typeof ApiPublicSyncHotmartRoute
  '/api/public/sync/trigger': typeof ApiPublicSyncTriggerRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRouteWithChildren
  '/agente': typeof AppAgenteRoute
  '/agente-ia': typeof AppAgenteIaRoute
  '/campanha': typeof AppCampanhaRoute
  '/coach': typeof AppCoachRouteWithChildren
  '/comissionamento': typeof AppComissionamentoRoute
  '/fechamento': typeof AppFechamentoRoute
  '/fechamento-semanal': typeof AppFechamentoSemanalRoute
  '/indicacoes': typeof AppIndicacoesRoute
  '/leads-dia': typeof AppLeadsDiaRoute
  '/ranking': typeof AppRankingRoute
  '/usuarios': typeof AppUsuariosRoute
  '/api/conversa-prova': typeof ApiConversaProvaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/': typeof AppIndexRoute
  '/coach/$id': typeof AppCoachIdRoute
  '/api/clint/webhook': typeof ApiClintWebhookRoute
  '/api/hotmart/webhook': typeof ApiHotmartWebhookRoute
  '/api/public/backfill-ai-exact': typeof ApiPublicBackfillAiExactRoute
  '/api/public/backfill-contact-tags': typeof ApiPublicBackfillContactTagsRoute
  '/api/public/backfill-v3': typeof ApiPublicBackfillV3Route
  '/api/public/hotmart-debug': typeof ApiPublicHotmartDebugRoute
  '/api/public/hotmart-probe': typeof ApiPublicHotmartProbeRoute
  '/api/public/hotmart-raw': typeof ApiPublicHotmartRawRoute
  '/arena': typeof AppArenaIndexRoute
  '/arena/sim/$id': typeof AppArenaSimIdRoute
  '/api/public/admin/manual-sale': typeof ApiPublicAdminManualSaleRoute
  '/api/public/agenda/availability': typeof ApiPublicAgendaAvailabilityRoute
  '/api/public/agenda/book': typeof ApiPublicAgendaBookRoute
  '/api/public/audit/manual-sales': typeof ApiPublicAuditManualSalesRoute
  '/api/public/sync/ccpbx': typeof ApiPublicSyncCcpbxRoute
  '/api/public/sync/coach-auto': typeof ApiPublicSyncCoachAutoRoute
  '/api/public/sync/coach-v3': typeof ApiPublicSyncCoachV3Route
  '/api/public/sync/contact-tags': typeof ApiPublicSyncContactTagsRoute
  '/api/public/sync/hotmart': typeof ApiPublicSyncHotmartRoute
  '/api/public/sync/trigger': typeof ApiPublicSyncTriggerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/auth': typeof AuthRouteWithChildren
  '/_app/agente': typeof AppAgenteRoute
  '/_app/agente-ia': typeof AppAgenteIaRoute
  '/_app/campanha': typeof AppCampanhaRoute
  '/_app/coach': typeof AppCoachRouteWithChildren
  '/_app/comissionamento': typeof AppComissionamentoRoute
  '/_app/fechamento': typeof AppFechamentoRoute
  '/_app/fechamento-semanal': typeof AppFechamentoSemanalRoute
  '/_app/indicacoes': typeof AppIndicacoesRoute
  '/_app/leads-dia': typeof AppLeadsDiaRoute
  '/_app/ranking': typeof AppRankingRoute
  '/_app/usuarios': typeof AppUsuariosRoute
  '/api/conversa-prova': typeof ApiConversaProvaRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/_app/': typeof AppIndexRoute
  '/_app/coach/$id': typeof AppCoachIdRoute
  '/api/clint/webhook': typeof ApiClintWebhookRoute
  '/api/hotmart/webhook': typeof ApiHotmartWebhookRoute
  '/api/public/backfill-ai-exact': typeof ApiPublicBackfillAiExactRoute
  '/api/public/backfill-contact-tags': typeof ApiPublicBackfillContactTagsRoute
  '/api/public/backfill-v3': typeof ApiPublicBackfillV3Route
  '/api/public/hotmart-debug': typeof ApiPublicHotmartDebugRoute
  '/api/public/hotmart-probe': typeof ApiPublicHotmartProbeRoute
  '/api/public/hotmart-raw': typeof ApiPublicHotmartRawRoute
  '/_app/arena/': typeof AppArenaIndexRoute
  '/_app/arena/sim/$id': typeof AppArenaSimIdRoute
  '/api/public/admin/manual-sale': typeof ApiPublicAdminManualSaleRoute
  '/api/public/agenda/availability': typeof ApiPublicAgendaAvailabilityRoute
  '/api/public/agenda/book': typeof ApiPublicAgendaBookRoute
  '/api/public/audit/manual-sales': typeof ApiPublicAuditManualSalesRoute
  '/api/public/sync/ccpbx': typeof ApiPublicSyncCcpbxRoute
  '/api/public/sync/coach-auto': typeof ApiPublicSyncCoachAutoRoute
  '/api/public/sync/coach-v3': typeof ApiPublicSyncCoachV3Route
  '/api/public/sync/contact-tags': typeof ApiPublicSyncContactTagsRoute
  '/api/public/sync/hotmart': typeof ApiPublicSyncHotmartRoute
  '/api/public/sync/trigger': typeof ApiPublicSyncTriggerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agente'
    | '/agente-ia'
    | '/campanha'
    | '/coach'
    | '/comissionamento'
    | '/fechamento'
    | '/fechamento-semanal'
    | '/indicacoes'
    | '/leads-dia'
    | '/ranking'
    | '/usuarios'
    | '/api/conversa-prova'
    | '/auth/callback'
    | '/coach/$id'
    | '/api/clint/webhook'
    | '/api/hotmart/webhook'
    | '/api/public/backfill-ai-exact'
    | '/api/public/backfill-contact-tags'
    | '/api/public/backfill-v3'
    | '/api/public/hotmart-debug'
    | '/api/public/hotmart-probe'
    | '/api/public/hotmart-raw'
    | '/arena/'
    | '/arena/sim/$id'
    | '/api/public/admin/manual-sale'
    | '/api/public/agenda/availability'
    | '/api/public/agenda/book'
    | '/api/public/audit/manual-sales'
    | '/api/public/sync/ccpbx'
    | '/api/public/sync/coach-auto'
    | '/api/public/sync/coach-v3'
    | '/api/public/sync/contact-tags'
    | '/api/public/sync/hotmart'
    | '/api/public/sync/trigger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/agente'
    | '/agente-ia'
    | '/campanha'
    | '/coach'
    | '/comissionamento'
    | '/fechamento'
    | '/fechamento-semanal'
    | '/indicacoes'
    | '/leads-dia'
    | '/ranking'
    | '/usuarios'
    | '/api/conversa-prova'
    | '/auth/callback'
    | '/'
    | '/coach/$id'
    | '/api/clint/webhook'
    | '/api/hotmart/webhook'
    | '/api/public/backfill-ai-exact'
    | '/api/public/backfill-contact-tags'
    | '/api/public/backfill-v3'
    | '/api/public/hotmart-debug'
    | '/api/public/hotmart-probe'
    | '/api/public/hotmart-raw'
    | '/arena'
    | '/arena/sim/$id'
    | '/api/public/admin/manual-sale'
    | '/api/public/agenda/availability'
    | '/api/public/agenda/book'
    | '/api/public/audit/manual-sales'
    | '/api/public/sync/ccpbx'
    | '/api/public/sync/coach-auto'
    | '/api/public/sync/coach-v3'
    | '/api/public/sync/contact-tags'
    | '/api/public/sync/hotmart'
    | '/api/public/sync/trigger'
  id:
    | '__root__'
    | '/_app'
    | '/auth'
    | '/_app/agente'
    | '/_app/agente-ia'
    | '/_app/campanha'
    | '/_app/coach'
    | '/_app/comissionamento'
    | '/_app/fechamento'
    | '/_app/fechamento-semanal'
    | '/_app/indicacoes'
    | '/_app/leads-dia'
    | '/_app/ranking'
    | '/_app/usuarios'
    | '/api/conversa-prova'
    | '/auth/callback'
    | '/_app/'
    | '/_app/coach/$id'
    | '/api/clint/webhook'
    | '/api/hotmart/webhook'
    | '/api/public/backfill-ai-exact'
    | '/api/public/backfill-contact-tags'
    | '/api/public/backfill-v3'
    | '/api/public/hotmart-debug'
    | '/api/public/hotmart-probe'
    | '/api/public/hotmart-raw'
    | '/_app/arena/'
    | '/_app/arena/sim/$id'
    | '/api/public/admin/manual-sale'
    | '/api/public/agenda/availability'
    | '/api/public/agenda/book'
    | '/api/public/audit/manual-sales'
    | '/api/public/sync/ccpbx'
    | '/api/public/sync/coach-auto'
    | '/api/public/sync/coach-v3'
    | '/api/public/sync/contact-tags'
    | '/api/public/sync/hotmart'
    | '/api/public/sync/trigger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
  ApiConversaProvaRoute: typeof ApiConversaProvaRoute
  ApiClintWebhookRoute: typeof ApiClintWebhookRoute
  ApiHotmartWebhookRoute: typeof ApiHotmartWebhookRoute
  ApiPublicBackfillAiExactRoute: typeof ApiPublicBackfillAiExactRoute
  ApiPublicBackfillContactTagsRoute: typeof ApiPublicBackfillContactTagsRoute
  ApiPublicBackfillV3Route: typeof ApiPublicBackfillV3Route
  ApiPublicHotmartDebugRoute: typeof ApiPublicHotmartDebugRoute
  ApiPublicHotmartProbeRoute: typeof ApiPublicHotmartProbeRoute
  ApiPublicHotmartRawRoute: typeof ApiPublicHotmartRawRoute
  ApiPublicAdminManualSaleRoute: typeof ApiPublicAdminManualSaleRoute
  ApiPublicAgendaAvailabilityRoute: typeof ApiPublicAgendaAvailabilityRoute
  ApiPublicAgendaBookRoute: typeof ApiPublicAgendaBookRoute
  ApiPublicAuditManualSalesRoute: typeof ApiPublicAuditManualSalesRoute
  ApiPublicSyncCcpbxRoute: typeof ApiPublicSyncCcpbxRoute
  ApiPublicSyncCoachAutoRoute: typeof ApiPublicSyncCoachAutoRoute
  ApiPublicSyncCoachV3Route: typeof ApiPublicSyncCoachV3Route
  ApiPublicSyncContactTagsRoute: typeof ApiPublicSyncContactTagsRoute
  ApiPublicSyncHotmartRoute: typeof ApiPublicSyncHotmartRoute
  ApiPublicSyncTriggerRoute: typeof ApiPublicSyncTriggerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/api/conversa-prova': {
      id: '/api/conversa-prova'
      path: '/api/conversa-prova'
      fullPath: '/api/conversa-prova'
      preLoaderRoute: typeof ApiConversaProvaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/usuarios': {
      id: '/_app/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof AppUsuariosRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ranking': {
      id: '/_app/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof AppRankingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/leads-dia': {
      id: '/_app/leads-dia'
      path: '/leads-dia'
      fullPath: '/leads-dia'
      preLoaderRoute: typeof AppLeadsDiaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/indicacoes': {
      id: '/_app/indicacoes'
      path: '/indicacoes'
      fullPath: '/indicacoes'
      preLoaderRoute: typeof AppIndicacoesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fechamento-semanal': {
      id: '/_app/fechamento-semanal'
      path: '/fechamento-semanal'
      fullPath: '/fechamento-semanal'
      preLoaderRoute: typeof AppFechamentoSemanalRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/fechamento': {
      id: '/_app/fechamento'
      path: '/fechamento'
      fullPath: '/fechamento'
      preLoaderRoute: typeof AppFechamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/comissionamento': {
      id: '/_app/comissionamento'
      path: '/comissionamento'
      fullPath: '/comissionamento'
      preLoaderRoute: typeof AppComissionamentoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/coach': {
      id: '/_app/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof AppCoachRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/campanha': {
      id: '/_app/campanha'
      path: '/campanha'
      fullPath: '/campanha'
      preLoaderRoute: typeof AppCampanhaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agente-ia': {
      id: '/_app/agente-ia'
      path: '/agente-ia'
      fullPath: '/agente-ia'
      preLoaderRoute: typeof AppAgenteIaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/agente': {
      id: '/_app/agente'
      path: '/agente'
      fullPath: '/agente'
      preLoaderRoute: typeof AppAgenteRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/arena/': {
      id: '/_app/arena/'
      path: '/arena'
      fullPath: '/arena/'
      preLoaderRoute: typeof AppArenaIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/public/hotmart-raw': {
      id: '/api/public/hotmart-raw'
      path: '/api/public/hotmart-raw'
      fullPath: '/api/public/hotmart-raw'
      preLoaderRoute: typeof ApiPublicHotmartRawRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotmart-probe': {
      id: '/api/public/hotmart-probe'
      path: '/api/public/hotmart-probe'
      fullPath: '/api/public/hotmart-probe'
      preLoaderRoute: typeof ApiPublicHotmartProbeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hotmart-debug': {
      id: '/api/public/hotmart-debug'
      path: '/api/public/hotmart-debug'
      fullPath: '/api/public/hotmart-debug'
      preLoaderRoute: typeof ApiPublicHotmartDebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-v3': {
      id: '/api/public/backfill-v3'
      path: '/api/public/backfill-v3'
      fullPath: '/api/public/backfill-v3'
      preLoaderRoute: typeof ApiPublicBackfillV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-contact-tags': {
      id: '/api/public/backfill-contact-tags'
      path: '/api/public/backfill-contact-tags'
      fullPath: '/api/public/backfill-contact-tags'
      preLoaderRoute: typeof ApiPublicBackfillContactTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/backfill-ai-exact': {
      id: '/api/public/backfill-ai-exact'
      path: '/api/public/backfill-ai-exact'
      fullPath: '/api/public/backfill-ai-exact'
      preLoaderRoute: typeof ApiPublicBackfillAiExactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/hotmart/webhook': {
      id: '/api/hotmart/webhook'
      path: '/api/hotmart/webhook'
      fullPath: '/api/hotmart/webhook'
      preLoaderRoute: typeof ApiHotmartWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/clint/webhook': {
      id: '/api/clint/webhook'
      path: '/api/clint/webhook'
      fullPath: '/api/clint/webhook'
      preLoaderRoute: typeof ApiClintWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/coach/$id': {
      id: '/_app/coach/$id'
      path: '/$id'
      fullPath: '/coach/$id'
      preLoaderRoute: typeof AppCoachIdRouteImport
      parentRoute: typeof AppCoachRoute
    }
    '/api/public/sync/trigger': {
      id: '/api/public/sync/trigger'
      path: '/api/public/sync/trigger'
      fullPath: '/api/public/sync/trigger'
      preLoaderRoute: typeof ApiPublicSyncTriggerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/hotmart': {
      id: '/api/public/sync/hotmart'
      path: '/api/public/sync/hotmart'
      fullPath: '/api/public/sync/hotmart'
      preLoaderRoute: typeof ApiPublicSyncHotmartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/contact-tags': {
      id: '/api/public/sync/contact-tags'
      path: '/api/public/sync/contact-tags'
      fullPath: '/api/public/sync/contact-tags'
      preLoaderRoute: typeof ApiPublicSyncContactTagsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/coach-v3': {
      id: '/api/public/sync/coach-v3'
      path: '/api/public/sync/coach-v3'
      fullPath: '/api/public/sync/coach-v3'
      preLoaderRoute: typeof ApiPublicSyncCoachV3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/coach-auto': {
      id: '/api/public/sync/coach-auto'
      path: '/api/public/sync/coach-auto'
      fullPath: '/api/public/sync/coach-auto'
      preLoaderRoute: typeof ApiPublicSyncCoachAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/sync/ccpbx': {
      id: '/api/public/sync/ccpbx'
      path: '/api/public/sync/ccpbx'
      fullPath: '/api/public/sync/ccpbx'
      preLoaderRoute: typeof ApiPublicSyncCcpbxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/audit/manual-sales': {
      id: '/api/public/audit/manual-sales'
      path: '/api/public/audit/manual-sales'
      fullPath: '/api/public/audit/manual-sales'
      preLoaderRoute: typeof ApiPublicAuditManualSalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agenda/book': {
      id: '/api/public/agenda/book'
      path: '/api/public/agenda/book'
      fullPath: '/api/public/agenda/book'
      preLoaderRoute: typeof ApiPublicAgendaBookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/agenda/availability': {
      id: '/api/public/agenda/availability'
      path: '/api/public/agenda/availability'
      fullPath: '/api/public/agenda/availability'
      preLoaderRoute: typeof ApiPublicAgendaAvailabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/admin/manual-sale': {
      id: '/api/public/admin/manual-sale'
      path: '/api/public/admin/manual-sale'
      fullPath: '/api/public/admin/manual-sale'
      preLoaderRoute: typeof ApiPublicAdminManualSaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/arena/sim/$id': {
      id: '/_app/arena/sim/$id'
      path: '/arena/sim/$id'
      fullPath: '/arena/sim/$id'
      preLoaderRoute: typeof AppArenaSimIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppCoachRouteChildren {
  AppCoachIdRoute: typeof AppCoachIdRoute
}

const AppCoachRouteChildren: AppCoachRouteChildren = {
  AppCoachIdRoute: AppCoachIdRoute,
}

const AppCoachRouteWithChildren = AppCoachRoute._addFileChildren(
  AppCoachRouteChildren,
)

interface AppRouteChildren {
  AppAgenteRoute: typeof AppAgenteRoute
  AppAgenteIaRoute: typeof AppAgenteIaRoute
  AppCampanhaRoute: typeof AppCampanhaRoute
  AppCoachRoute: typeof AppCoachRouteWithChildren
  AppComissionamentoRoute: typeof AppComissionamentoRoute
  AppFechamentoRoute: typeof AppFechamentoRoute
  AppFechamentoSemanalRoute: typeof AppFechamentoSemanalRoute
  AppIndicacoesRoute: typeof AppIndicacoesRoute
  AppLeadsDiaRoute: typeof AppLeadsDiaRoute
  AppRankingRoute: typeof AppRankingRoute
  AppUsuariosRoute: typeof AppUsuariosRoute
  AppIndexRoute: typeof AppIndexRoute
  AppArenaIndexRoute: typeof AppArenaIndexRoute
  AppArenaSimIdRoute: typeof AppArenaSimIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAgenteRoute: AppAgenteRoute,
  AppAgenteIaRoute: AppAgenteIaRoute,
  AppCampanhaRoute: AppCampanhaRoute,
  AppCoachRoute: AppCoachRouteWithChildren,
  AppComissionamentoRoute: AppComissionamentoRoute,
  AppFechamentoRoute: AppFechamentoRoute,
  AppFechamentoSemanalRoute: AppFechamentoSemanalRoute,
  AppIndicacoesRoute: AppIndicacoesRoute,
  AppLeadsDiaRoute: AppLeadsDiaRoute,
  AppRankingRoute: AppRankingRoute,
  AppUsuariosRoute: AppUsuariosRoute,
  AppIndexRoute: AppIndexRoute,
  AppArenaIndexRoute: AppArenaIndexRoute,
  AppArenaSimIdRoute: AppArenaSimIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
  ApiConversaProvaRoute: ApiConversaProvaRoute,
  ApiClintWebhookRoute: ApiClintWebhookRoute,
  ApiHotmartWebhookRoute: ApiHotmartWebhookRoute,
  ApiPublicBackfillAiExactRoute: ApiPublicBackfillAiExactRoute,
  ApiPublicBackfillContactTagsRoute: ApiPublicBackfillContactTagsRoute,
  ApiPublicBackfillV3Route: ApiPublicBackfillV3Route,
  ApiPublicHotmartDebugRoute: ApiPublicHotmartDebugRoute,
  ApiPublicHotmartProbeRoute: ApiPublicHotmartProbeRoute,
  ApiPublicHotmartRawRoute: ApiPublicHotmartRawRoute,
  ApiPublicAdminManualSaleRoute: ApiPublicAdminManualSaleRoute,
  ApiPublicAgendaAvailabilityRoute: ApiPublicAgendaAvailabilityRoute,
  ApiPublicAgendaBookRoute: ApiPublicAgendaBookRoute,
  ApiPublicAuditManualSalesRoute: ApiPublicAuditManualSalesRoute,
  ApiPublicSyncCcpbxRoute: ApiPublicSyncCcpbxRoute,
  ApiPublicSyncCoachAutoRoute: ApiPublicSyncCoachAutoRoute,
  ApiPublicSyncCoachV3Route: ApiPublicSyncCoachV3Route,
  ApiPublicSyncContactTagsRoute: ApiPublicSyncContactTagsRoute,
  ApiPublicSyncHotmartRoute: ApiPublicSyncHotmartRoute,
  ApiPublicSyncTriggerRoute: ApiPublicSyncTriggerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
